kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: list-jobs
  namespace: default
subjects:
- kind: User
  name: system:serviceaccount:default:default # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: jobs-lister
  apiGroup: rbac.authorization.k8s.io
